[package]
name = "identity_new_resolver"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.86"
thiserror.workspace = true
compound_resolver = { path = "../compound_resolver" }

[lints]
workspace = true

[dev-dependencies]
tokio = { version = "1.38.0", features = ["macros", "rt"] }
