[package]
name = "identity_resolver"
version = "1.3.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.86"
thiserror.workspace = true
identity_iota_core = { version = "=1.3.0", path = "../identity_iota_core", optional = true }
identity_did = { version = "=1.3.0", path = "../identity_did", optional = true }
iota-sdk = { version = "1.1.5", default-features = false, features = ["client"], optional = true }

[lints]
workspace = true

[dev-dependencies]
tokio = { version = "1.38.0", features = ["macros", "rt"] }

[features]
default = ["iota"]
iota = ["dep:iota-sdk", "dep:identity_iota_core", "dep:identity_did"]
